"""City -> (ICAO station, unit, IANA timezone) for Polymarket daily temperature markets."""
STATIONS = {
    'amsterdam': ('EHAM', 'C', 'Europe/Amsterdam'), 'ankara': ('LTAC', 'C', 'Europe/Istanbul'),
    'atlanta': ('KATL', 'F', 'America/New_York'), 'austin': ('KAUS', 'F', 'America/Chicago'),
    'beijing': ('ZBAA', 'C', 'Asia/Shanghai'), 'buenos-aires': ('SAEZ', 'C', 'America/Argentina/Buenos_Aires'),
    'busan': ('RKPK', 'C', 'Asia/Seoul'), 'cape-town': ('FACT', 'C', 'Africa/Johannesburg'),
    'chengdu': ('ZUUU', 'C', 'Asia/Shanghai'), 'chicago': ('KORD', 'F', 'America/Chicago'),
    'chongqing': ('ZUCK', 'C', 'Asia/Shanghai'), 'dallas': ('KDAL', 'F', 'America/Chicago'),
    'denver': ('KBKF', 'F', 'America/Denver'), 'guangzhou': ('ZGGG', 'C', 'Asia/Shanghai'),
    'helsinki': ('EFHK', 'C', 'Europe/Helsinki'), 'hong-kong': ('VHHH', 'C', 'Asia/Hong_Kong'),
    'houston': ('KHOU', 'F', 'America/Chicago'), 'istanbul': ('LTFM', 'C', 'Europe/Istanbul'),
    'jeddah': ('OEJN', 'C', 'Asia/Riyadh'), 'jinan': ('ZSJN', 'C', 'Asia/Shanghai'),
    'karachi': ('OPKC', 'C', 'Asia/Karachi'), 'kuala-lumpur': ('WMKK', 'C', 'Asia/Kuala_Lumpur'),
    'london': ('EGLC', 'C', 'Europe/London'), 'los-angeles': ('KLAX', 'F', 'America/Los_Angeles'),
    'lucknow': ('VILK', 'C', 'Asia/Kolkata'), 'madrid': ('LEMD', 'C', 'Europe/Madrid'),
    'manila': ('RPLL', 'C', 'Asia/Manila'), 'mexico-city': ('MMMX', 'C', 'America/Mexico_City'),
    'miami': ('KMIA', 'F', 'America/New_York'), 'milan': ('LIMC', 'C', 'Europe/Rome'),
    'moscow': ('UUWW', 'C', 'Europe/Moscow'), 'munich': ('EDDM', 'C', 'Europe/Berlin'),
    'nyc': ('KLGA', 'F', 'America/New_York'), 'panama-city': ('MPMG', 'C', 'America/Panama'),
    'paris': ('LFPB', 'C', 'Europe/Paris'), 'qingdao': ('ZSQD', 'C', 'Asia/Shanghai'),
    'san-francisco': ('KSFO', 'F', 'America/Los_Angeles'), 'sao-paulo': ('SBGR', 'C', 'America/Sao_Paulo'),
    'seattle': ('KSEA', 'F', 'America/Los_Angeles'), 'seoul': ('RKSI', 'C', 'Asia/Seoul'),
    'shanghai': ('ZSPD', 'C', 'Asia/Shanghai'), 'shenzhen': ('ZGSZ', 'C', 'Asia/Shanghai'),
    'singapore': ('WSSS', 'C', 'Asia/Singapore'), 'taipei': ('RCSS', 'C', 'Asia/Taipei'),
    'tel-aviv': ('LLBG', 'C', 'Asia/Jerusalem'), 'tokyo': ('RJTT', 'C', 'Asia/Tokyo'),
    'toronto': ('CYYZ', 'C', 'America/Toronto'), 'warsaw': ('EPWA', 'C', 'Europe/Warsaw'),
    'wellington': ('NZWN', 'C', 'Pacific/Auckland'), 'wuhan': ('ZHHH', 'C', 'Asia/Shanghai'),
    'zhengzhou': ('ZHCC', 'C', 'Asia/Shanghai'), 'lagos': ('DNMM', 'C', 'Africa/Lagos'),
}
